# Site settings
title: Azaé
baseline: Catalyseur d'agilité
email: contact@azae.net
baseurl: ""
url: "http://azae.net"
twitter_username: azae_net
github_username:  azae


# Build settings
markdown: kramdown


gems:
- jekyll-paginate


defaults:
- scope:
   path: "articles"
   type: "posts"
  values:
    permalink: /articles/:title
    layout: post

exclude:
- README.md
- Dockerfile
- Gemfile