# Site settings
title: Azaé
email: contact@azae.net
description: > # this means to ignore newlines until "baseurl:"
  Spécialiste devops, coaching agile
baseurl: ""
url: "http://azae.net"
twitter_username: azae_net
github_username:  azae

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "/blog/page:num/"


baseline: "Catalyseur d'agilité"