# Site settings
title: Azaé
email: contact@azae.net
description: > # this means to ignore newlines until "baseurl:"
  Spécialiste devops, coaching agile
baseurl: ""
url: "http://azae.net"
twitter_username: azae_net
github_username:  azae

# Build settings
markdown: kramdown

baseline: "Catalyseur d'agilité"

gems:
- jekyll-paginate


defaults:
- scope:
   path: "articles"
   type: "posts"
  values:
    permalink: /articles/:title
    layout: post
