
- title: Introduction aux méthodes agiles
  description: "Découvrir les méthodes agiles et en expérimenter des pratiques"
  tags: [methods, beginers]
  présentation: |
    Cette formation de deux jours a pour objectifs de faire découvrir les bases de l'agilité : sa philosophie, ses pratiques, la raison d'être et comment l'implémenter. Elle est destinée aux équipes IT qui souhaitente entamer ou poursuivre une transformation vers l'agilité. Cette introduction à l'agilité s'adapte aux différentes équipes et reste une occasion pour tous de découvrir, d'approfondir ou d'enrichir sa conaissance de l'agiité et des différents possibles.
  objective: |
  - initiation aux pratiques agiles 
  - comprendre et utiliser les principales méthodes agiles  -
  prerequists: |
  - Avoir participé à un projet informatique
  - Avoir de l'autonomie et de la motivation
  duration: 2 jours alternant théorie et *pratique sur vos projets*.
  plan: |
  - Pourquoi l'agilité ?
  - Un peu d'histoire
  - Présentation générale
  - Les rôles
  - Définir les besoins
  - Gérer l'itération
  - Quelques bonnes pratiques
  
- title: Devops
  description: "Comprendre la philosophie Devops et son implication dans une organisation"
  tags: [methods, beginers]

- title: Introduction à Docker par la pratique
  description: "Découvrir Docker et les container applicatifs en deux jours de pratiques"
  tags: [technical, beginers]
présentation: |
  Cette formation de 2 jours vous fournira une introduction à Docker et aux dernières technologies de conteneurs applicatifs. Elle est destinée aux administrateurs et aux développeurs souhaitant appréhender l'utilisation des conteneurs applicatifs. *L'ensemble des travaux pratiques seront réalisés sur vos projets*. Cette approche pratique axée sur les cas concrets de vos entreprises permet une meilleure assimilation. *La formation est illustrée* de nombreux cas d'utilisation directement tirés *de notre expérience*, pipeline de déploiement continu, cloud privé, automatisation du poste de développement, etc.
  objective: |
    - Appréhender l'utilisation de Docker
    - Comprendre et utiliser Docker au sein de vos projets
  prerequists: |
    - Avoir participé à un projet informatique
    - Avoir de l'autonomie et de la motivation
    - Quelques bases en shell
  duration: 2 jours alternant théorie et *pratique sur vos projets*.
  plan: |
    - Pourquoi Docker ?
    - Principe de fonctionnement de Docker (cycle de vie du conteneur et découverte de l'API)
    - Créer des conteneurs Docker
    - Gérer des containers et des images Docker
    - Orchestration des containers
    - Docker et la sécurité
    - L'intégration avec les autres outils du marché
http://deliverous.com/assets/documents/formation-docker.pdf

- title: Software craftmanship
  description: "S'initier aux bonnes pratiques de l'artisanat logiciel"
  tags: [technical, beginers]

- title: Intelligence Collective
  description: "Découvrir les outils de l'intelligence collective et apprendre à les mettre en œuvre"
  tags: [methods, beginers]

- title: Git par la pratique
  description: "4h pour découvrir git et ses secrets"
  tags: [technical, beginers]

- title: Le leadership agile
  description: "Appréhender les clés de la direction agile"
  tags: [methods]
